
CREATE TABLE login(
	id int auto_increment,
	nome varchar(20),
	senha varchar(20),
	primary key(id)
);

CREATE TABLE produtos (
	ID int auto_increment,
	nome varchar(50) not null,
	descricao varchar(50),
	quantidade int,
	/* 10 dígitos de precisão e 3 após a vírgula */
	preco real(10, 3),
	primary key(ID)
);

INSERT INTO produtos (nome, descricao, quantidade, preco) VALUES ("Glibenclamida","5MG", 10, 15055);
INSERT INTO produtos (nome, descricao, quantidade, preco) VALUES ("Insulina Humana ","100UI/ML", 10, 450.99);
INSERT INTO produtos (nome, descricao, quantidade, preco) VALUES ("Insulina Humana Regular","100UI/ML", 20, 550.98);
INSERT INTO produtos (nome, descricao, quantidade, preco) VALUES ("Sulfato de Salbutamol","5MG", 15, 50.5);
INSERT INTO produtos (nome, descricao, quantidade, preco) VALUES ("Dipropionato de Beclometsona","50MCG", 50, 85.55);



INSERT INTO login (nome,senha) VALUES ("admin","admin");
INSERT INTO login (nome,senha) VALUES ("Igor","Yoshio");
INSERT INTO login (nome,senha) VALUES ("Fuller","Charlotte");
INSERT INTO login (nome,senha) VALUES ("Vernon","Hector");
INSERT INTO login (nome,senha) VALUES ("Ulla","Hedwig");
INSERT INTO login (nome,senha) VALUES ("Leandra","Lucas");
INSERT INTO login (nome,senha) VALUES ("Deborah","Azalia");
INSERT INTO login (nome,senha) VALUES ("Jared","Barbara");
INSERT INTO login (nome,senha) VALUES ("Diana","Camden");
INSERT INTO login (nome,senha) VALUES ("Ethan","Upton");
INSERT INTO login (nome,senha) VALUES ("Reese","Idola");
INSERT INTO login (nome,senha) VALUES ("Gil","Ramona");
INSERT INTO login (nome,senha) VALUES ("Alvin","Courtney");
INSERT INTO login (nome,senha) VALUES ("September","Thaddeus");
INSERT INTO login (nome,senha) VALUES ("Doris","Anne");
INSERT INTO login (nome,senha) VALUES ("Xander","Melissa");
INSERT INTO login (nome,senha) VALUES ("Vivien","Graiden");
INSERT INTO login (nome,senha) VALUES ("Allistair","Norman");
INSERT INTO login (nome,senha) VALUES ("Alvin","Leandra");
INSERT INTO login (nome,senha) VALUES ("Malik","Mari");
INSERT INTO login (nome,senha) VALUES ("Roth","Yvonne");
INSERT INTO login (nome,senha) VALUES ("Amir","Catherine");
INSERT INTO login (nome,senha) VALUES ("Brynn","Aurelia");
INSERT INTO login (nome,senha) VALUES ("Macon","Jocelyn");
INSERT INTO login (nome,senha) VALUES ("Nissim","Hayfa");
INSERT INTO login (nome,senha) VALUES ("Helen","Wade");
INSERT INTO login (nome,senha) VALUES ("Mohammad","Nelle");
INSERT INTO login (nome,senha) VALUES ("Driscoll","Angelica");
INSERT INTO login (nome,senha) VALUES ("Ray","Todd");
INSERT INTO login (nome,senha) VALUES ("Pandora","Nehru");
INSERT INTO login (nome,senha) VALUES ("Chancellor","Indigo");
INSERT INTO login (nome,senha) VALUES ("Ann","David");
INSERT INTO login (nome,senha) VALUES ("Laith","Anthony");
INSERT INTO login (nome,senha) VALUES ("Rhea","Adrienne");
INSERT INTO login (nome,senha) VALUES ("Astra","Ava");
INSERT INTO login (nome,senha) VALUES ("Solomon","Nehru");
INSERT INTO login (nome,senha) VALUES ("Cheryl","Elijah");
INSERT INTO login (nome,senha) VALUES ("Boris","Abbot");
INSERT INTO login (nome,senha) VALUES ("Philip","Ezekiel");
INSERT INTO login (nome,senha) VALUES ("Mikayla","Charles");
INSERT INTO login (nome,senha) VALUES ("Sophia","Lucius");
INSERT INTO login (nome,senha) VALUES ("Joy","Idona");
INSERT INTO login (nome,senha) VALUES ("Azalia","Travis");
INSERT INTO login (nome,senha) VALUES ("Rebecca","Minerva");
INSERT INTO login (nome,senha) VALUES ("Judah","Ayanna");
INSERT INTO login (nome,senha) VALUES ("Cameron","Stephen");
INSERT INTO login (nome,senha) VALUES ("Upton","Quynn");
INSERT INTO login (nome,senha) VALUES ("Dante","Riley");
INSERT INTO login (nome,senha) VALUES ("Octavia","Paki");
INSERT INTO login (nome,senha) VALUES ("Mia","Wynter");
INSERT INTO login (nome,senha) VALUES ("Ariana","Ariel");
INSERT INTO login (nome,senha) VALUES ("Olympia","Dennis");
INSERT INTO login (nome,senha) VALUES ("Harding","Brynn");
INSERT INTO login (nome,senha) VALUES ("David","Flynn");
INSERT INTO login (nome,senha) VALUES ("Dominique","Jerry");
INSERT INTO login (nome,senha) VALUES ("Lillith","Sylvester");
INSERT INTO login (nome,senha) VALUES ("Jerry","Evan");
INSERT INTO login (nome,senha) VALUES ("Jayme","Xandra");
INSERT INTO login (nome,senha) VALUES ("Ulysses","Wendy");
INSERT INTO login (nome,senha) VALUES ("Sonia","Naomi");
INSERT INTO login (nome,senha) VALUES ("Tamekah","Walter");
INSERT INTO login (nome,senha) VALUES ("Candace","Gavin");
INSERT INTO login (nome,senha) VALUES ("Alexander","Quynn");
INSERT INTO login (nome,senha) VALUES ("Miranda","Byron");
INSERT INTO login (nome,senha) VALUES ("Xyla","Caleb");
INSERT INTO login (nome,senha) VALUES ("Natalie","Natalie");
INSERT INTO login (nome,senha) VALUES ("Ifeoma","Silas");
INSERT INTO login (nome,senha) VALUES ("Martina","Kenneth");
INSERT INTO login (nome,senha) VALUES ("Christine","Kimberly");
INSERT INTO login (nome,senha) VALUES ("Donovan","Keefe");
INSERT INTO login (nome,senha) VALUES ("Branden","Dalton");
INSERT INTO login (nome,senha) VALUES ("Yoko","Jacob");
INSERT INTO login (nome,senha) VALUES ("Donovan","Philip");
INSERT INTO login (nome,senha) VALUES ("Hayfa","Scarlett");
INSERT INTO login (nome,senha) VALUES ("Matthew","Macaulay");
INSERT INTO login (nome,senha) VALUES ("Mara","Robin");
INSERT INTO login (nome,senha) VALUES ("Arsenio","Forrest");
INSERT INTO login (nome,senha) VALUES ("Rajah","Grady");
INSERT INTO login (nome,senha) VALUES ("Yasir","Lenore");
INSERT INTO login (nome,senha) VALUES ("Octavia","Ferris");
INSERT INTO login (nome,senha) VALUES ("Yvonne","Xanthus");
INSERT INTO login (nome,senha) VALUES ("Harriet","Heather");
INSERT INTO login (nome,senha) VALUES ("Madonna","Idola");
INSERT INTO login (nome,senha) VALUES ("Maile","Uriah");
INSERT INTO login (nome,senha) VALUES ("Keiko","Audrey");
INSERT INTO login (nome,senha) VALUES ("Kirk","Xavier");
INSERT INTO login (nome,senha) VALUES ("Finn","Tarik");
INSERT INTO login (nome,senha) VALUES ("Carlos","Alisa");
INSERT INTO login (nome,senha) VALUES ("Odette","Honorato");
INSERT INTO login (nome,senha) VALUES ("Sebastian","Mary");
INSERT INTO login (nome,senha) VALUES ("Isabelle","Blake");
INSERT INTO login (nome,senha) VALUES ("Flavia","Rahim");
INSERT INTO login (nome,senha) VALUES ("Sigourney","Venus");
INSERT INTO login (nome,senha) VALUES ("Hilda","Jason");
INSERT INTO login (nome,senha) VALUES ("Ivor","Madonna");
INSERT INTO login (nome,senha) VALUES ("Allen","Melodie");
INSERT INTO login (nome,senha) VALUES ("Alden","Jonah");
INSERT INTO login (nome,senha) VALUES ("Amery","Jeremy");
INSERT INTO login (nome,senha) VALUES ("Iona","Levi");
INSERT INTO login (nome,senha) VALUES ("Ivor","Nicole");
INSERT INTO login (nome,senha) VALUES ("Marsden","Solomon");
INSERT INTO login (nome,senha) VALUES ("Hilel","Demetria");
INSERT INTO login (nome,senha) VALUES ("Drake","Isaiah");
INSERT INTO login (nome,senha) VALUES ("Sybil","Mason");
INSERT INTO login (nome,senha) VALUES ("Miranda","Zachary");
INSERT INTO login (nome,senha) VALUES ("Cooper","Melodie");
INSERT INTO login (nome,senha) VALUES ("Trevor","Paula");
INSERT INTO login (nome,senha) VALUES ("Willow","Hannah");
INSERT INTO login (nome,senha) VALUES ("Baker","Steel");
INSERT INTO login (nome,senha) VALUES ("Timothy","Carter");
INSERT INTO login (nome,senha) VALUES ("Sarah","Kyra");
INSERT INTO login (nome,senha) VALUES ("Aphrodite","Nayda");
INSERT INTO login (nome,senha) VALUES ("Theodore","Fatima");
INSERT INTO login (nome,senha) VALUES ("Jared","Aidan");
INSERT INTO login (nome,senha) VALUES ("Armando","Ulysses");
INSERT INTO login (nome,senha) VALUES ("Clio","Baker");
INSERT INTO login (nome,senha) VALUES ("Shaine","Blair");
INSERT INTO login (nome,senha) VALUES ("Forrest","Caesar");
INSERT INTO login (nome,senha) VALUES ("Brandon","Gay");
INSERT INTO login (nome,senha) VALUES ("Gisela","Jane");
INSERT INTO login (nome,senha) VALUES ("Burke","Tate");
INSERT INTO login (nome,senha) VALUES ("Renee","Chelsea");
INSERT INTO login (nome,senha) VALUES ("Stone","Hope");
INSERT INTO login (nome,senha) VALUES ("Rahim","Alfonso");
INSERT INTO login (nome,senha) VALUES ("Rahim","Armando");
INSERT INTO login (nome,senha) VALUES ("Naomi","Nehru");
INSERT INTO login (nome,senha) VALUES ("Luke","Zephr");
INSERT INTO login (nome,senha) VALUES ("Amber","Damon");
INSERT INTO login (nome,senha) VALUES ("Michael","Lacy");
INSERT INTO login (nome,senha) VALUES ("Dane","Anastasia");
INSERT INTO login (nome,senha) VALUES ("Shay","Bree");
INSERT INTO login (nome,senha) VALUES ("Bert","Cairo");
INSERT INTO login (nome,senha) VALUES ("Whitney","Dane");
INSERT INTO login (nome,senha) VALUES ("Alexander","Blaine");
INSERT INTO login (nome,senha) VALUES ("Petra","Cally");
INSERT INTO login (nome,senha) VALUES ("Duncan","Kirby");
INSERT INTO login (nome,senha) VALUES ("Axel","Angela");
INSERT INTO login (nome,senha) VALUES ("Vance","Steven");
INSERT INTO login (nome,senha) VALUES ("Karleigh","India");
INSERT INTO login (nome,senha) VALUES ("Ivor","Garth");
INSERT INTO login (nome,senha) VALUES ("Imani","Jolene");
INSERT INTO login (nome,senha) VALUES ("Nola","Carl");
INSERT INTO login (nome,senha) VALUES ("Yolanda","Abel");
INSERT INTO login (nome,senha) VALUES ("Faith","Elizabeth");
INSERT INTO login (nome,senha) VALUES ("Lev","Damian");
INSERT INTO login (nome,senha) VALUES ("Zenaida","Reagan");
INSERT INTO login (nome,senha) VALUES ("Griffin","Brian");
INSERT INTO login (nome,senha) VALUES ("Susan","Shaine");
INSERT INTO login (nome,senha) VALUES ("Kasper","Zeus");
INSERT INTO login (nome,senha) VALUES ("Kaseem","Wallace");
INSERT INTO login (nome,senha) VALUES ("Zane","Nathan");
INSERT INTO login (nome,senha) VALUES ("Kennan","Tatiana");
INSERT INTO login (nome,senha) VALUES ("Lois","Malcolm");
INSERT INTO login (nome,senha) VALUES ("Drew","Fiona");
INSERT INTO login (nome,senha) VALUES ("Beverly","Shafira");
INSERT INTO login (nome,senha) VALUES ("Macaulay","Iona");
INSERT INTO login (nome,senha) VALUES ("Astra","Quyn");
INSERT INTO login (nome,senha) VALUES ("Ralph","Samuel");
INSERT INTO login (nome,senha) VALUES ("Nolan","Hyacinth");
INSERT INTO login (nome,senha) VALUES ("Jenna","Hayley");
INSERT INTO login (nome,senha) VALUES ("Christian","Ross");
INSERT INTO login (nome,senha) VALUES ("Diana","Amelia");
INSERT INTO login (nome,senha) VALUES ("Lacota","Savannah");
INSERT INTO login (nome,senha) VALUES ("Norman","Maisie");
INSERT INTO login (nome,senha) VALUES ("Cody","Ginger");
INSERT INTO login (nome,senha) VALUES ("Tanya","Ryder");
INSERT INTO login (nome,senha) VALUES ("Laurel","Kermit");
INSERT INTO login (nome,senha) VALUES ("Joshua","Carol");
INSERT INTO login (nome,senha) VALUES ("Oliver","Sonya");
INSERT INTO login (nome,senha) VALUES ("Kelsey","William");
INSERT INTO login (nome,senha) VALUES ("Madeson","Kasimir");
INSERT INTO login (nome,senha) VALUES ("Karyn","Lacey");
INSERT INTO login (nome,senha) VALUES ("Keiko","Sarah");
INSERT INTO login (nome,senha) VALUES ("Graiden","Wallace");
INSERT INTO login (nome,senha) VALUES ("Tanner","Bruce");
INSERT INTO login (nome,senha) VALUES ("Mallory","Amelia");
INSERT INTO login (nome,senha) VALUES ("Coby","Sonya");
INSERT INTO login (nome,senha) VALUES ("Aubrey","Aline");
INSERT INTO login (nome,senha) VALUES ("Hammett","Macy");
INSERT INTO login (nome,senha) VALUES ("Ronan","Bruno");
INSERT INTO login (nome,senha) VALUES ("Quon","Elton");
INSERT INTO login (nome,senha) VALUES ("Kelly","Silas");
INSERT INTO login (nome,senha) VALUES ("Howard","Alexander");
INSERT INTO login (nome,senha) VALUES ("Rudyard","Sean");
INSERT INTO login (nome,senha) VALUES ("Cooper","Blythe");
INSERT INTO login (nome,senha) VALUES ("Daphne","Charde");
INSERT INTO login (nome,senha) VALUES ("Shaeleigh","Shaine");
INSERT INTO login (nome,senha) VALUES ("Erasmus","Mufutau");
INSERT INTO login (nome,senha) VALUES ("Kameko","Hiram");
INSERT INTO login (nome,senha) VALUES ("Ila","Sonia");
INSERT INTO login (nome,senha) VALUES ("Lunea","Rebekah");
INSERT INTO login (nome,senha) VALUES ("Edan","Geoffrey");
INSERT INTO login (nome,senha) VALUES ("MacKensie","Silas");
INSERT INTO login (nome,senha) VALUES ("Myra","Rhoda");
INSERT INTO login (nome,senha) VALUES ("Tashya","Ethan");
INSERT INTO login (nome,senha) VALUES ("Russell","Brody");
INSERT INTO login (nome,senha) VALUES ("Fay","Jessamine");
INSERT INTO login (nome,senha) VALUES ("Haviva","Constance");
INSERT INTO login (nome,senha) VALUES ("Howard","Nehru");
